### ISSUE TITLE
Tutorial Page

### ISSUE THREAD

**Issue by MusayevKamran** [chrisleekr/yii2-ngx-boilerplate#10]
Hello

This is awesome project. Will be any tutorials website about this project and will you update this project?

**Comment by chrisleekr** [comment]
Hi @MusayevKamran 

I am not sure what kind of tutorial you need. 
If you have any good idea, welcome your input.

**Comment by MusayevKamran** [comment]
There are some error and it is hard to me to find out this. Firstly i cant sign in with user account. admin and staff work fine. then get or post always show bad request.  Thanks for replying

![error](https://user-images.githubusercontent.com/17671445/35215933-4d3606c2-ff7f-11e7-927e-10f5c31c132c.png)

**Comment by MusayevKamran** [comment]
{"name":"Bad Request","message":"The system could not process your request. Please check and try again.","code":0,"status":400,"type":"yii\\web\\BadRequestHttpException"}

**Comment by chrisleekr** [comment]
Hi @MusayevKamran 

That is valid. I think it is misleading error message. 

If you try to access `http://api.boilerplate.local/ping`, then you must see `pong` message.
