### ISSUE TITLE
Ngix won't start in docker-composer up -d 

### ISSUE THREAD

**Issue by primo1108** [chrisleekr/yii2-ngx-boilerplate#11]
When installing

everything else seemed to install fine after using docker-composer up -d

I encountered following error.

`ERROR: for nginx  Cannot start service nginx: b'Mounts denied: \r\nThe paths /Applications/MAMP/htdocs/yii2-ngx-boilerplate/nginx/image-files/etc/nginx/nginx.conf and /Applications/MAMP/htdocs/yii2-ngx-boilerplate/nginx\r\nare not shared from OS X and are not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'
`

**Comment by chrisleekr** [comment]
Hi @primo1108 

You need to share `/Applications/MAMP/htdocs/yii2-ngx-boilerplate` folder with docker as error message described.

```You can configure shared paths from Docker -> Preferences... -> File Sharing.```

**Comment by primo1108** [comment]
Thanks @chrisleekr , 
It worked!
