### ISSUE TITLE
Do you plan to setup a dockerized version

### ISSUE THREAD

**Issue by philippfrenzel** [chrisleekr/yii2-ngx-boilerplate#5]
Hey, 

like the boilerplate! Do you plan to integrate it with docker? 

Thx Philipp

**Comment by chrisleekr** [comment]
Hi @philippfrenzel 

Yap, when I get a time, I will dockerize this application. :)
Or if someone interested, can do now!

**Comment by chrisleekr** [comment]
I dockerized the application.
