### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by 2E5** [chrisleekr/yii2-ngx-boilerplate#8]
Hey,

This project is really great, I'm appreciate you put it online.

1. I fund a small error on API.     
Path: _\api\vendor\bower-asset_ did't exist. 
I had to change folder name  _bower-asset_ --> _bower_ and now it working correct.

2. When i try to login or register for any account on Frontend or Backend, appears the communique _"[object Object]"_ :

![backend](https://user-images.githubusercontent.com/34648749/34103782-5041b070-e3ee-11e7-8f2f-7e7a0804c4fc.png)
![api](https://user-images.githubusercontent.com/34648749/34103781-5024958a-e3ee-11e7-91d6-c06d4bd2a29d.png)

**This is my project:** https://wetransfer.com/downloads/8888e95e63e95420a5d03d40cbabb28c20171218113942/49b46cf6168a75df5e8adcc24f095aaf20171218113942/3232f3

I would be very grateful if you could help me fix it.

Thx Pawel

**Comment by MusayevKamran** [comment]
when i try to register or to enter admin panel it shows this error

Sorry, there was a connection error occurred. Please try again.

**Comment by chrisleekr** [comment]
Hi @2E5, 
Sorry for late reply.

1. Have you run the command `composer install` or `composer update` to install packages?

2. Can you open the console panel in the browser and let me know with the error message?

**Comment by chrisleekr** [comment]
Hi @MusayevKamran 

It means, Angular frontend was not able to access to API. 

Have you configured the API correctly?
